FROM nikolaik/python-nodejs:python3.8-nodejs12-alpine

RUN mkdir /app
WORKDIR /app

RUN \
  npm config set registry http://registry.npm.taobao.org && \
  npm config set proxy http://192.168.2.211:7890  && \
  npm install node-sass

RUN echo "https://mirrors.ustc.edu.cn/alpine/latest-stable/main" > /etc/apk/repositories && \
    echo "https://mirrors.ustc.edu.cn/alpine/latest-stable/community" >> /etc/apk/repositories && \
    apk update

RUN apk add build-base libffi-dev postgresql-dev

COPY requirements.txt .

RUN \
  cd /app && \
  pip install gunicorn && \
  pip install -r requirements.txt

COPY . .

RUN \
  cd /app/client && \
  npm install node-sass && \
  npm ci && \
  npm run build

RUN \
  chmod +x /app/run.sh && \
  chmod +x /app/verify_env.py && \
  chmod +x /app/verify_data_migrations.py

EXPOSE 5000
ENTRYPOINT "./run.sh"