FROM nikolaik/python-nodejs:python3.8-nodejs12-alpine

RUN mkdir /app
WORKDIR /app

COPY . .

RUN echo "https://mirror.tuna.tsinghua.edu.cn/alpine/latest-stable/main" > /etc/apk/repositories && \
    echo "https://mirror.tuna.tsinghua.edu.cn/alpine/latest-stable/community" >> /etc/apk/repositories && \
    apk update

RUN apk add build-base libffi-dev postgresql-dev

RUN \
  cd /app && \
  pip install gunicorn && \
  pip install -r requirements.txt && \
  chmod +x run.sh && \
  chmod +x verify_env.py && \
  chmod +x verify_data_migrations.py

RUN \
  cd /app/client && \
  npm config set registry http://registry.npm.taobao.org && \
  npm config set proxy http://192.168.2.211:7890  && \
  npm install node-sass && \
  npm ci && \
  npm run build


EXPOSE 5000
ENTRYPOINT "./run.sh"%